# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cev_sim.headless.v1 import headless_pb2 as cev__sim_dot_headless_dot_v1_dot_headless__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cev_sim/headless/v1/headless_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeadlessSimulationServiceStub:
    """Language-neutral control contract for deterministic headless simulation.
    The schema is transport-independent even though the first implementation
    will expose it through gRPC over Unix-domain sockets or TCP.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/GetCapabilities',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.CreateBatch = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/CreateBatch',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CreateBatchRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CreateBatchResponse.FromString,
                _registered_method=True)
        self.ResetBatch = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/ResetBatch',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.ResetBatchRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.ResetBatchResponse.FromString,
                _registered_method=True)
        self.StepBatch = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/StepBatch',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.StepBatchRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.StepBatchResponse.FromString,
                _registered_method=True)
        self.FinalizeBatch = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/FinalizeBatch',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.FinalizeBatchRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.FinalizeBatchResponse.FromString,
                _registered_method=True)
        self.CloseBatch = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/CloseBatch',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CloseBatchRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CloseBatchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cev_sim.headless.v1.HeadlessSimulationService/Health',
                request_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.HealthRequest.SerializeToString,
                response_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.HealthResponse.FromString,
                _registered_method=True)


class HeadlessSimulationServiceServicer:
    """Language-neutral control contract for deterministic headless simulation.
    The schema is transport-independent even though the first implementation
    will expose it through gRPC over Unix-domain sockets or TCP.
    """

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeadlessSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'CreateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBatch,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CreateBatchRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CreateBatchResponse.SerializeToString,
            ),
            'ResetBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetBatch,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.ResetBatchRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.ResetBatchResponse.SerializeToString,
            ),
            'StepBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.StepBatch,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.StepBatchRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.StepBatchResponse.SerializeToString,
            ),
            'FinalizeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeBatch,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.FinalizeBatchRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.FinalizeBatchResponse.SerializeToString,
            ),
            'CloseBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseBatch,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CloseBatchRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.CloseBatchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.HealthRequest.FromString,
                    response_serializer=cev__sim_dot_headless_dot_v1_dot_headless__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cev_sim.headless.v1.HeadlessSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cev_sim.headless.v1.HeadlessSimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeadlessSimulationService:
    """Language-neutral control contract for deterministic headless simulation.
    The schema is transport-independent even though the first implementation
    will expose it through gRPC over Unix-domain sockets or TCP.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/GetCapabilities',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.GetCapabilitiesRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/CreateBatch',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.CreateBatchRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.CreateBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/ResetBatch',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.ResetBatchRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.ResetBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/StepBatch',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.StepBatchRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.StepBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/FinalizeBatch',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.FinalizeBatchRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.FinalizeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/CloseBatch',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.CloseBatchRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.CloseBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cev_sim.headless.v1.HeadlessSimulationService/Health',
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.HealthRequest.SerializeToString,
            cev__sim_dot_headless_dot_v1_dot_headless__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
