import { UNIT_CATALOG_META } from "./UnitCatalog.meta";
import NumberUnit from "./units/math/Number";
import { CalculationUnit } from "./units/math/Calculation";
import { Float64ToInt32, Int32ToFloat64 } from "./units/conversions/NumberConversions";
import {
    BooleanToFloatUnit,
    BooleanToIntUnit,
    BooleanToStringUnit,
    CeilToIntUnit,
    FloatToBooleanUnit,
    FloatToStringUnit,
    FloorToIntUnit,
    IntToBooleanUnit,
    IntToStringUnit,
    ParseJsonUnit,
    RoadIdToStringUnit,
    RoundToIntUnit,
    StringifyJsonUnit,
    StringToBooleanUnit,
    StringToFloatUnit,
    StringToIntUnit,
    StringToRoadIdUnit,
    StringToTextureIdUnit,
    TextureIdToStringUnit,
    ToStringUnit,
    TruncateToIntUnit,
} from "./units/conversions/Conversions";
import {
    ConcatStringUnit,
    JoinStringUnit,
    LowercaseStringUnit,
    ReplaceStringUnit,
    SliceStringUnit,
    SplitStringUnit,
    StringContainsUnit,
    StringEndsWithUnit,
    StringLengthUnit,
    StringStartsWithUnit,
    TrimStringUnit,
    UppercaseStringUnit,
} from "./units/strings/StringBlocks";
import {
    JsonDeleteUnit,
    JsonGetUnit,
    JsonHasUnit,
    JsonMergeUnit,
    JsonSetUnit,
} from "./units/objects/JsonBlocks";
import {
    ArrayAppendUnit,
    ArrayConcatUnit,
    ArrayContainsUnit,
    ArrayGetUnit,
    ArrayLengthUnit,
    ArrayLiteralUnit,
    ArraySetUnit,
    ArraySliceUnit,
    LinspaceUnit,
} from "./units/collections/ArrayBlocks";
import { E, GoldenRatio, PI, Tau } from "./units/math/Constants";
import {
    AbsoluteUnit,
    AcosUnit,
    AddUnit,
    AsinUnit,
    Atan2Unit,
    AtanUnit,
    ClampUnit,
    CosUnit,
    DeadbandUnit,
    DegreesToRadiansUnit,
    DivideUnit,
    ExponentialUnit,
    IntegerUnit,
    InverseLerpUnit,
    JsonUnit,
    LerpUnit,
    Log10Unit,
    MaximumUnit,
    MinimumUnit,
    ModuloUnit,
    MultiplyUnit,
    NaturalLogUnit,
    NegateUnit,
    PowerUnit,
    RadiansToDegreesUnit,
    SignUnit,
    SinUnit,
    SmoothstepUnit,
    SquareRootUnit,
    SubtractUnit,
    TanUnit,
    WrapRadiansUnit,
} from "./units/math/ScalarBlocks";
import {
    AndUnit,
    BooleanUnit,
    EqualUnit,
    GreaterEqualUnit,
    GreaterUnit,
    IsFiniteUnit,
    LessEqualUnit,
    LessUnit,
    NearlyEqualUnit,
    NotEqualUnit,
    NotUnit,
    OrUnit,
    XorUnit,
} from "./units/statements/LogicBlocks";
import { RandomNumber } from "./units/math/Random";
import { Noise } from "./units/math/tex/Noise";
import {
    AddTextureUnit,
    ClampTextureUnit,
    InvertTextureUnit,
    MultiplyTex,
    Scale,
    ScaleTextureUnit,
    SubtractTextureUnit,
} from "./units/math/tex/Scale";
import { Mask } from "./units/math/tex/Mask";
import { IfUnit } from "./units/statements/If";
import { Conjugation, Equality } from "./units/statements/Equality";
import { IgnoreUnit, NopUnit, PassthroughUnit, SequenceUnit } from "./units/statements/Unit";
import { RepeatProgramUnit } from "./units/statements/RepeatProgram";
import { StringUnit } from "./units/objects/String";
import { TextureImportUnit } from "./units/objects/TextureImport";
import {
    BlendTextureUnit,
    HeightToSlopeUnit,
    NormalizeTextureUnit,
    TerrainNoiseUnit,
    TerraceTextureUnit,
} from "./units/math/Terrain";
import {
    LowPassFilterUnit,
    RateLimiterUnit,
    SampleTextureUnit,
    SensorFusionUnit,
    ThresholdGateUnit,
} from "./units/math/SensorFlow";
import {
    GaussianNoiseUnit,
    JitterUnit,
    RandomRangeUnit,
    RemapRangeUnit,
    SeededRandomUnit,
    WeightedSelectUnit,
} from "./units/math/Randomization";
import { OutputNodeUnit, ProgramInputUnit } from "./units/program/ProgramIO";
import {
    AddVec2Unit,
    AddVec3Unit,
    CrossVec3Unit,
    DistanceVec2Unit,
    DistanceVec3Unit,
    DotVec2Unit,
    DotVec3Unit,
    LengthVec2Unit,
    LengthVec3Unit,
    MakePose2DUnit,
    MakePose3DUnit,
    MakeVec2Unit,
    MakeVec3Unit,
    NormalizeVec2Unit,
    NormalizeVec3Unit,
    ScaleVec2Unit,
    ScaleVec3Unit,
    SplitPose2DUnit,
    SplitPose3DUnit,
    SplitVec2Unit,
    SplitVec3Unit,
    SubtractVec2Unit,
    SubtractVec3Unit,
} from "./units/geometry/GeometryBlocks";
import {
    DebounceUnit,
    DerivativeUnit,
    FallingEdgeUnit,
    HysteresisUnit,
    IntegratorUnit,
    MedianFilterUnit,
    MovingAverageUnit,
    PreviousUnit,
    PulseUnit,
    RisingEdgeUnit,
    SlewRateUnit,
    StopwatchUnit,
    ValueChangedUnit,
} from "./units/control/TemporalBlocks";
import { PidControllerUnit } from "./units/control/ControllerBlocks";
import {
    DeviceStateUnit,
    ScenarioStatusUnit,
    SimulationClockUnit,
    VehicleStateUnit,
} from "./units/simulator/SimulatorAdapters";
import {
    FrameAlongPathUnit,
    GetNearestRoadUnit,
    SampleRoadUnit,
    ScatterFeaturesUnit,
    SpawnPropUnit,
} from "./units/world/WorldBlocks";
import { MakeActorCommandUnit, SplitActorCommandUnit } from "./units/mission/ActorCommand";
import {
    DistanceToRouteEndUnit,
    FollowRouteSectionUnit,
    FollowRouteUnit,
    RouteLengthUnit,
    RouteSectionCountUnit,
    RouteTangentUnit,
    SplitWaypointUnit,
    WaypointAtIndexUnit,
} from "./units/mission/RouteBlocks";
import {
    AdvanceWaypointUnit,
    AssertSignalUnit,
    BindInputUnit,
    BindingStatusUnit,
    BindOutputUnit,
    BindTriggerUnit,
    BuildTopicMessageUnit,
    CurrentWaypointUnit,
    DeviceSnapshotUnit,
    LogMessageUnit,
    LogSignalUnit,
    MissionStateUnit,
    ObjectSnapshotUnit,
    OnSignalUpdateUnit,
    OnTickUnit,
    OnTimerUnit,
    ProbeSignalUnit,
    ReadSignalUnit,
    ReachedWaypointUnit,
    RecordSignalUnit,
    ReplaySignalUnit,
    RouteProgressUnit,
    ScenarioFlagReadUnit,
    ScenarioFlagWriteUnit,
    ScenarioSnapshotUnit,
    SetMissionStateUnit,
    SignalAgeUnit,
    SignalChangedUnit,
    SignalDefaultUnit,
    SignalExistsUnit,
    SignalLatchUnit,
    SimulationSnapshotUnit,
    StagePublishUnit,
    StoreNamespaceUnit,
    TopicFieldUnit,
    TopicMetadataUnit,
    TopicSnapshotUnit,
    TopicStaleGateUnit,
    VehicleDimensionsUnit,
    VehiclePoseUnit,
    VehicleSnapshotUnit,
    VehicleVelocityUnit,
    WaypointListUnit,
    WriteSignalUnit,
} from "./units/signals/SignalBlocks";

const COMPONENT_BY_TYPE = new Map([
    ["NumberUnitClass", NumberUnit],
    ["CalculationBlock", CalculationUnit],
    ["RandomNumberBlock", RandomNumber],
    ["PIBlock", PI],
    ["EBlock", E],
    ["TauBlock", Tau],
    ["GoldenRatioBlock", GoldenRatio],
    ["IntegerBlock", IntegerUnit],
    ["AddBlock", AddUnit],
    ["SubtractBlock", SubtractUnit],
    ["MultiplyBlock", MultiplyUnit],
    ["DivideBlock", DivideUnit],
    ["ModuloBlock", ModuloUnit],
    ["PowerBlock", PowerUnit],
    ["MinimumBlock", MinimumUnit],
    ["MaximumBlock", MaximumUnit],
    ["NegateBlock", NegateUnit],
    ["AbsoluteBlock", AbsoluteUnit],
    ["SignBlock", SignUnit],
    ["SquareRootBlock", SquareRootUnit],
    ["ExponentialBlock", ExponentialUnit],
    ["NaturalLogBlock", NaturalLogUnit],
    ["Log10Block", Log10Unit],
    ["ClampBlock", ClampUnit],
    ["LerpBlock", LerpUnit],
    ["InverseLerpBlock", InverseLerpUnit],
    ["SmoothstepBlock", SmoothstepUnit],
    ["DeadbandBlock", DeadbandUnit],
    ["SinBlock", SinUnit],
    ["CosBlock", CosUnit],
    ["TanBlock", TanUnit],
    ["AsinBlock", AsinUnit],
    ["AcosBlock", AcosUnit],
    ["AtanBlock", AtanUnit],
    ["DegreesToRadiansBlock", DegreesToRadiansUnit],
    ["RadiansToDegreesBlock", RadiansToDegreesUnit],
    ["WrapRadiansBlock", WrapRadiansUnit],
    ["Atan2Block", Atan2Unit],
    ["MakeVec2Block", MakeVec2Unit],
    ["SplitVec2Block", SplitVec2Unit],
    ["AddVec2Block", AddVec2Unit],
    ["SubtractVec2Block", SubtractVec2Unit],
    ["ScaleVec2Block", ScaleVec2Unit],
    ["DotVec2Block", DotVec2Unit],
    ["LengthVec2Block", LengthVec2Unit],
    ["NormalizeVec2Block", NormalizeVec2Unit],
    ["DistanceVec2Block", DistanceVec2Unit],
    ["MakeVec3Block", MakeVec3Unit],
    ["SplitVec3Block", SplitVec3Unit],
    ["AddVec3Block", AddVec3Unit],
    ["SubtractVec3Block", SubtractVec3Unit],
    ["ScaleVec3Block", ScaleVec3Unit],
    ["DotVec3Block", DotVec3Unit],
    ["LengthVec3Block", LengthVec3Unit],
    ["NormalizeVec3Block", NormalizeVec3Unit],
    ["DistanceVec3Block", DistanceVec3Unit],
    ["CrossVec3Block", CrossVec3Unit],
    ["MakePose2DBlock", MakePose2DUnit],
    ["SplitPose2DBlock", SplitPose2DUnit],
    ["MakePose3DBlock", MakePose3DUnit],
    ["SplitPose3DBlock", SplitPose3DUnit],
    ["BooleanBlock", BooleanUnit],
    ["NotBlock", NotUnit],
    ["AndBlock", AndUnit],
    ["OrBlock", OrUnit],
    ["XorBlock", XorUnit],
    ["EqualBlock", EqualUnit],
    ["NotEqualBlock", NotEqualUnit],
    ["LessBlock", LessUnit],
    ["LessEqualBlock", LessEqualUnit],
    ["GreaterBlock", GreaterUnit],
    ["GreaterEqualBlock", GreaterEqualUnit],
    ["NearlyEqualBlock", NearlyEqualUnit],
    ["IsFiniteBlock", IsFiniteUnit],
    ["PreviousBlock", PreviousUnit],
    ["ValueChangedBlock", ValueChangedUnit],
    ["RisingEdgeBlock", RisingEdgeUnit],
    ["FallingEdgeBlock", FallingEdgeUnit],
    ["DebounceBlock", DebounceUnit],
    ["HysteresisBlock", HysteresisUnit],
    ["PulseBlock", PulseUnit],
    ["StopwatchBlock", StopwatchUnit],
    ["MovingAverageBlock", MovingAverageUnit],
    ["MedianFilterBlock", MedianFilterUnit],
    ["SlewRateBlock", SlewRateUnit],
    ["IntegratorBlock", IntegratorUnit],
    ["DerivativeBlock", DerivativeUnit],
    ["PidControllerBlock", PidControllerUnit],
    ["JsonBlock", JsonUnit],
    ["JsonGetBlock", JsonGetUnit],
    ["JsonSetBlock", JsonSetUnit],
    ["JsonHasBlock", JsonHasUnit],
    ["JsonDeleteBlock", JsonDeleteUnit],
    ["JsonMergeBlock", JsonMergeUnit],
    ["NoiseBlock", Noise],
    ["MaskBlock", Mask],
    ["MultiplyTexBlock", MultiplyTex],
    ["ScaleBlock", Scale],
    ["ScaleTextureBlock", ScaleTextureUnit],
    ["AddTextureBlock", AddTextureUnit],
    ["SubtractTextureBlock", SubtractTextureUnit],
    ["ClampTextureBlock", ClampTextureUnit],
    ["InvertTextureBlock", InvertTextureUnit],
    ["TerrainNoiseBlock", TerrainNoiseUnit],
    ["NormalizeTextureBlock", NormalizeTextureUnit],
    ["BlendTextureBlock", BlendTextureUnit],
    ["TerraceTextureBlock", TerraceTextureUnit],
    ["HeightToSlopeBlock", HeightToSlopeUnit],
    ["SampleTextureBlock", SampleTextureUnit],
    ["LowPassFilterBlock", LowPassFilterUnit],
    ["RateLimiterBlock", RateLimiterUnit],
    ["SensorFusionBlock", SensorFusionUnit],
    ["ThresholdGateBlock", ThresholdGateUnit],
    ["RandomRangeBlock", RandomRangeUnit],
    ["SeededRandomBlock", SeededRandomUnit],
    ["GaussianNoiseBlock", GaussianNoiseUnit],
    ["JitterBlock", JitterUnit],
    ["WeightedSelectBlock", WeightedSelectUnit],
    ["RemapRangeBlock", RemapRangeUnit],
    ["Float64ToInt32Block", Float64ToInt32],
    ["Int32ToFloat64Block", Int32ToFloat64],
    ["FloorToIntBlock", FloorToIntUnit],
    ["CeilToIntBlock", CeilToIntUnit],
    ["RoundToIntBlock", RoundToIntUnit],
    ["TruncateToIntBlock", TruncateToIntUnit],
    ["BooleanToIntBlock", BooleanToIntUnit],
    ["BooleanToFloatBlock", BooleanToFloatUnit],
    ["IntToBooleanBlock", IntToBooleanUnit],
    ["FloatToBooleanBlock", FloatToBooleanUnit],
    ["FloatToStringBlock", FloatToStringUnit],
    ["IntToStringBlock", IntToStringUnit],
    ["BooleanToStringBlock", BooleanToStringUnit],
    ["ToStringBlock", ToStringUnit],
    ["StringToFloatBlock", StringToFloatUnit],
    ["StringToIntBlock", StringToIntUnit],
    ["StringToBooleanBlock", StringToBooleanUnit],
    ["ParseJsonBlock", ParseJsonUnit],
    ["StringifyJsonBlock", StringifyJsonUnit],
    ["StringToRoadIdBlock", StringToRoadIdUnit],
    ["RoadIdToStringBlock", RoadIdToStringUnit],
    ["StringToTextureIdBlock", StringToTextureIdUnit],
    ["TextureIdToStringBlock", TextureIdToStringUnit],
    ["StringBlock", StringUnit],
    ["TextureImportBlock", TextureImportUnit],
    ["ConcatStringBlock", ConcatStringUnit],
    ["StringLengthBlock", StringLengthUnit],
    ["StringContainsBlock", StringContainsUnit],
    ["StringStartsWithBlock", StringStartsWithUnit],
    ["StringEndsWithBlock", StringEndsWithUnit],
    ["TrimStringBlock", TrimStringUnit],
    ["LowercaseStringBlock", LowercaseStringUnit],
    ["UppercaseStringBlock", UppercaseStringUnit],
    ["SliceStringBlock", SliceStringUnit],
    ["ReplaceStringBlock", ReplaceStringUnit],
    ["SplitStringBlock", SplitStringUnit],
    ["JoinStringBlock", JoinStringUnit],
    ["ArrayLiteralBlock", ArrayLiteralUnit],
    ["ArrayLengthBlock", ArrayLengthUnit],
    ["ArrayGetBlock", ArrayGetUnit],
    ["ArraySetBlock", ArraySetUnit],
    ["ArrayAppendBlock", ArrayAppendUnit],
    ["ArrayConcatBlock", ArrayConcatUnit],
    ["ArraySliceBlock", ArraySliceUnit],
    ["ArrayContainsBlock", ArrayContainsUnit],
    ["LinspaceBlock", LinspaceUnit],
    ["IfBlock", IfUnit],
    ["EqualityBlock", Equality],
    ["ConjugationBlock", Conjugation],
    ["NopBlock", NopUnit],
    ["IgnoreBlock", IgnoreUnit],
    ["SequenceBlock", SequenceUnit],
    ["PassthroughBlock", PassthroughUnit],
    ["RepeatProgramBlock", RepeatProgramUnit],
    ["ProgramInputBlock", ProgramInputUnit],
    ["OutputNodeBlock", OutputNodeUnit],
    ["ReadSignalBlock", ReadSignalUnit],
    ["WriteSignalBlock", WriteSignalUnit],
    ["SignalExistsBlock", SignalExistsUnit],
    ["SignalAgeBlock", SignalAgeUnit],
    ["SignalChangedBlock", SignalChangedUnit],
    ["SignalLatchBlock", SignalLatchUnit],
    ["SignalDefaultBlock", SignalDefaultUnit],
    ["StoreNamespaceBlock", StoreNamespaceUnit],
    ["TopicSnapshotBlock", TopicSnapshotUnit],
    ["TopicFieldBlock", TopicFieldUnit],
    ["BuildTopicMessageBlock", BuildTopicMessageUnit],
    ["StagePublishBlock", StagePublishUnit],
    ["TopicStaleGateBlock", TopicStaleGateUnit],
    ["TopicMetadataBlock", TopicMetadataUnit],
    ["VehicleSnapshotBlock", VehicleSnapshotUnit],
    ["VehiclePoseBlock", VehiclePoseUnit],
    ["VehicleVelocityBlock", VehicleVelocityUnit],
    ["VehicleDimensionsBlock", VehicleDimensionsUnit],
    ["DeviceSnapshotBlock", DeviceSnapshotUnit],
    ["SimulationSnapshotBlock", SimulationSnapshotUnit],
    ["ScenarioSnapshotBlock", ScenarioSnapshotUnit],
    ["ObjectSnapshotBlock", ObjectSnapshotUnit],
    ["VehicleStateBlock", VehicleStateUnit],
    ["DeviceStateBlock", DeviceStateUnit],
    ["SimulationClockBlock", SimulationClockUnit],
    ["ScenarioStatusBlock", ScenarioStatusUnit],
    ["SampleRoadBlock", SampleRoadUnit],
    ["GetNearestRoadBlock", GetNearestRoadUnit],
    ["SpawnPropBlock", SpawnPropUnit],
    ["ScatterFeaturesBlock", ScatterFeaturesUnit],
    ["WaypointListBlock", WaypointListUnit],
    ["CurrentWaypointBlock", CurrentWaypointUnit],
    ["AdvanceWaypointBlock", AdvanceWaypointUnit],
    ["ReachedWaypointBlock", ReachedWaypointUnit],
    ["MissionStateBlock", MissionStateUnit],
    ["SetMissionStateBlock", SetMissionStateUnit],
    ["RouteProgressBlock", RouteProgressUnit],
    ["FollowRouteBlock", FollowRouteUnit],
    ["FollowRouteSectionBlock", FollowRouteSectionUnit],
    ["RouteSectionCountBlock", RouteSectionCountUnit],
    ["WaypointAtIndexBlock", WaypointAtIndexUnit],
    ["SplitWaypointBlock", SplitWaypointUnit],
    ["RouteLengthBlock", RouteLengthUnit],
    ["DistanceToRouteEndBlock", DistanceToRouteEndUnit],
    ["RouteTangentBlock", RouteTangentUnit],
    ["FrameAlongPathBlock", FrameAlongPathUnit],
    ["MakeActorCommandBlock", MakeActorCommandUnit],
    ["SplitActorCommandBlock", SplitActorCommandUnit],
    ["ScenarioFlagReadBlock", ScenarioFlagReadUnit],
    ["ScenarioFlagWriteBlock", ScenarioFlagWriteUnit],
    ["OnSignalUpdateBlock", OnSignalUpdateUnit],
    ["OnTickBlock", OnTickUnit],
    ["OnTimerBlock", OnTimerUnit],
    ["BindInputBlock", BindInputUnit],
    ["BindOutputBlock", BindOutputUnit],
    ["BindTriggerBlock", BindTriggerUnit],
    ["ProbeSignalBlock", ProbeSignalUnit],
    ["LogSignalBlock", LogSignalUnit],
    ["LogMessageBlock", LogMessageUnit],
    ["AssertSignalBlock", AssertSignalUnit],
    ["RecordSignalBlock", RecordSignalUnit],
    ["ReplaySignalBlock", ReplaySignalUnit],
    ["BindingStatusBlock", BindingStatusUnit],
]);

export function createCatalogUnitUUID() {
    if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
        return crypto.randomUUID();
    }
    return Math.random().toString(36).slice(2, 11);
}

export const UNIT_CATALOG = UNIT_CATALOG_META.map((entry) => ({
    ...entry,
    Component: COMPONENT_BY_TYPE.get(entry.type) || null,
}));

UNIT_CATALOG.forEach((entry) => {
    if (entry.placeable && (!entry.Component || !entry.blockClass)) {
        throw new Error(`Placeable unit "${entry.type}" requires both a React component and block class.`);
    }
});

export const UNIT_CATALOG_BY_TYPE = new Map(
    UNIT_CATALOG.map((entry) => [entry.type, entry]),
);

export function getUnitCatalogEntry(type) {
    return UNIT_CATALOG_BY_TYPE.get(type) || null;
}

export function groupedUnitCatalog() {
    return UNIT_CATALOG.reduce((groups, item) => {
        if (!item.placeable) return groups;
        if (!groups[item.category]) groups[item.category] = [];
        groups[item.category].push(item);
        return groups;
    }, {});
}

export function catalogBlockClasses() {
    return UNIT_CATALOG_META.map((entry) => entry.blockClass);
}
