/**
 * Server-safe unit catalog metadata (no React components).
 * Used by /api/scripting/units and MCP tooling.
 */
import { NumberUnitClass } from "./units/math/Number.block.js";
import { CalculationBlock } from "./units/math/Calculation.block.js";
import { Float64ToInt32Block, Int32ToFloat64Block } from "./units/conversions/NumberConversions.block.js";
import {
    BooleanToFloatBlock,
    BooleanToIntBlock,
    BooleanToStringBlock,
    CeilToIntBlock,
    FloatToBooleanBlock,
    FloatToStringBlock,
    FloorToIntBlock,
    IntToBooleanBlock,
    IntToStringBlock,
    ParseJsonBlock,
    RoadIdToStringBlock,
    RoundToIntBlock,
    StringifyJsonBlock,
    StringToBooleanBlock,
    StringToFloatBlock,
    StringToIntBlock,
    StringToRoadIdBlock,
    StringToTextureIdBlock,
    TextureIdToStringBlock,
    ToStringBlock,
    TruncateToIntBlock,
} from "./units/conversions/Conversions.block.js";
import {
    ConcatStringBlock,
    JoinStringBlock,
    LowercaseStringBlock,
    ReplaceStringBlock,
    SliceStringBlock,
    SplitStringBlock,
    StringContainsBlock,
    StringEndsWithBlock,
    StringLengthBlock,
    StringStartsWithBlock,
    TrimStringBlock,
    UppercaseStringBlock,
} from "./units/strings/StringBlocks.block.js";
import {
    JsonDeleteBlock,
    JsonGetBlock,
    JsonHasBlock,
    JsonMergeBlock,
    JsonSetBlock,
} from "./units/objects/JsonBlocks.block.js";
import {
    ArrayAppendBlock,
    ArrayConcatBlock,
    ArrayContainsBlock,
    ArrayGetBlock,
    ArrayLengthBlock,
    ArrayLiteralBlock,
    ArraySetBlock,
    ArraySliceBlock,
    LinspaceBlock,
} from "./units/collections/ArrayBlocks.block.js";
import { EBlock, GoldenRatioBlock, PIBlock, TauBlock } from "./units/math/Constants.block.js";
import {
    AbsoluteBlock,
    AcosBlock,
    AddBlock,
    AsinBlock,
    Atan2Block,
    AtanBlock,
    ClampBlock,
    CosBlock,
    DeadbandBlock,
    DegreesToRadiansBlock,
    DivideBlock,
    ExponentialBlock,
    IntegerBlock,
    InverseLerpBlock,
    JsonBlock,
    LerpBlock,
    Log10Block,
    MaximumBlock,
    MinimumBlock,
    ModuloBlock,
    MultiplyBlock,
    NaturalLogBlock,
    NegateBlock,
    PowerBlock,
    RadiansToDegreesBlock,
    SignBlock,
    SinBlock,
    SmoothstepBlock,
    SquareRootBlock,
    SubtractBlock,
    TanBlock,
    WrapRadiansBlock,
} from "./units/math/ScalarBlocks.block.js";
import {
    AndBlock,
    BooleanBlock,
    EqualBlock,
    GreaterBlock,
    GreaterEqualBlock,
    IsFiniteBlock,
    LessBlock,
    LessEqualBlock,
    NearlyEqualBlock,
    NotBlock,
    NotEqualBlock,
    OrBlock,
    XorBlock,
} from "./units/statements/LogicBlocks.block.js";
import { RandomNumberBlock } from "./units/math/Random.block.js";
import { NoiseBlock } from "./units/math/tex/Noise.block.js";
import {
    AddTextureBlock,
    ClampTextureBlock,
    InvertTextureBlock,
    MultiplyTexBlock,
    ScaleBlock,
    ScaleTextureBlock,
    SubtractTextureBlock,
} from "./units/math/tex/Scale.block.js";
import {
    DeviceStateBlock,
    ScenarioStatusBlock,
    SimulationClockBlock,
    VehicleStateBlock,
} from "./units/simulator/SimulatorAdapters.block.js";
import {
    FrameAlongPathBlock,
    GetNearestRoadBlock,
    SampleRoadBlock,
    ScatterFeaturesBlock,
    SpawnPropBlock,
} from "./units/world/WorldBlocks.block.js";
import { MaskBlock } from "./units/math/tex/Mask.block.js";
import { IfBlock } from "./units/statements/If.block.js";
import { ConjugationBlock, EqualityBlock } from "./units/statements/Equality.block.js";
import {
    IgnoreBlock,
    NopBlock,
    PassthroughBlock,
    SequenceBlock,
} from "./units/statements/Unit.block.js";
import { RepeatProgramBlock } from "./units/statements/RepeatProgram.block.js";
import { StringBlock } from "./units/objects/String.block.js";
import { TextureImportBlock } from "./units/objects/TextureImport.block.js";
import {
    BlendTextureBlock,
    HeightToSlopeBlock,
    NormalizeTextureBlock,
    TerrainNoiseBlock,
    TerraceTextureBlock,
} from "./units/math/Terrain.block.js";
import {
    LowPassFilterBlock,
    RateLimiterBlock,
    SampleTextureBlock,
    SensorFusionBlock,
    ThresholdGateBlock,
} from "./units/math/SensorFlow.block.js";
import {
    GaussianNoiseBlock,
    JitterBlock,
    RandomRangeBlock,
    RemapRangeBlock,
    SeededRandomBlock,
    WeightedSelectBlock,
} from "./units/math/Randomization.block.js";
import { OutputNodeBlock, ProgramInputBlock } from "./units/program/ProgramIO.block.js";
import {
    AddVec2Block,
    AddVec3Block,
    CrossVec3Block,
    DistanceVec2Block,
    DistanceVec3Block,
    DotVec2Block,
    DotVec3Block,
    LengthVec2Block,
    LengthVec3Block,
    MakePose2DBlock,
    MakePose3DBlock,
    MakeVec2Block,
    MakeVec3Block,
    NormalizeVec2Block,
    NormalizeVec3Block,
    ScaleVec2Block,
    ScaleVec3Block,
    SplitPose2DBlock,
    SplitPose3DBlock,
    SplitVec2Block,
    SplitVec3Block,
    SubtractVec2Block,
    SubtractVec3Block,
} from "./units/geometry/GeometryBlocks.block.js";
import {
    DebounceBlock,
    DerivativeBlock,
    FallingEdgeBlock,
    HysteresisBlock,
    IntegratorBlock,
    MedianFilterBlock,
    MovingAverageBlock,
    PreviousBlock,
    PulseBlock,
    RisingEdgeBlock,
    SlewRateBlock,
    StopwatchBlock,
    ValueChangedBlock,
} from "./units/control/TemporalBlocks.block.js";
import { PidControllerBlock } from "./units/control/ControllerBlocks.block.js";
import {
    MakeActorCommandBlock,
    SplitActorCommandBlock,
} from "./units/mission/ActorCommand.block.js";
import {
    DistanceToRouteEndBlock,
    FollowRouteBlock,
    FollowRouteSectionBlock,
    RouteLengthBlock,
    RouteSectionCountBlock,
    RouteTangentBlock,
    SplitWaypointBlock,
    WaypointAtIndexBlock,
} from "./units/mission/RouteBlocks.block.js";
import {
    AdvanceWaypointBlock,
    AssertSignalBlock,
    BindInputBlock,
    BindingStatusBlock,
    BindOutputBlock,
    BindTriggerBlock,
    BuildTopicMessageBlock,
    CurrentWaypointBlock,
    DeviceSnapshotBlock,
    LogMessageBlock,
    LogSignalBlock,
    MissionStateBlock,
    ObjectSnapshotBlock,
    OnSignalUpdateBlock,
    OnTickBlock,
    OnTimerBlock,
    ProbeSignalBlock,
    ReadSignalBlock,
    ReachedWaypointBlock,
    RecordSignalBlock,
    ReplaySignalBlock,
    RouteProgressBlock,
    ScenarioFlagReadBlock,
    ScenarioFlagWriteBlock,
    ScenarioSnapshotBlock,
    SetMissionStateBlock,
    SignalAgeBlock,
    SignalChangedBlock,
    SignalDefaultBlock,
    SignalExistsBlock,
    SignalLatchBlock,
    SimulationSnapshotBlock,
    StagePublishBlock,
    StoreNamespaceBlock,
    TopicFieldBlock,
    TopicMetadataBlock,
    TopicSnapshotBlock,
    TopicStaleGateBlock,
    VehicleDimensionsBlock,
    VehiclePoseBlock,
    VehicleSnapshotBlock,
    VehicleVelocityBlock,
    WaypointListBlock,
    WriteSignalBlock,
} from "./units/signals/SignalBlocks.block.js";

const NO_SETTINGS = Object.freeze([]);

const NUMBER_SETTINGS = Object.freeze([
    Object.freeze({ target: "storedData", key: null, valueType: "float64", default: 0 }),
]);
const INTEGER_SETTINGS = Object.freeze([
    Object.freeze({ target: "storedData", key: null, valueType: "int32", default: 0 }),
]);
const BOOLEAN_SETTINGS = Object.freeze([
    Object.freeze({ target: "storedData", key: null, valueType: "boolean", default: false }),
]);
const JSON_SETTINGS = Object.freeze([
    Object.freeze({ target: "storedData", key: null, valueType: "json", default: null }),
]);
const STRING_SETTINGS = Object.freeze([
    Object.freeze({ target: "storedData", key: null, valueType: "string", default: "" }),
]);
const EQUALITY_SETTINGS = Object.freeze([
    Object.freeze({
        target: "storedData",
        key: null,
        valueType: "enum",
        default: "eq",
        options: ["eq", "neq", "gt", "lt", "gte", "lte"],
    }),
]);
const CONJUGATION_SETTINGS = Object.freeze([
    Object.freeze({
        target: "storedData",
        key: null,
        valueType: "enum",
        default: "and",
        options: ["and", "or", "xor"],
    }),
]);
const PROGRAM_INPUT_SETTINGS = Object.freeze([
    Object.freeze({ target: "storedData", key: "label", valueType: "string", default: "input" }),
    Object.freeze({ target: "storedData", key: "type", valueType: "port_type", default: "float64" }),
    Object.freeze({ target: "storedData", key: "defaultValue", valueType: "string", default: "0" }),
]);
const OUTPUT_NODE_SETTINGS = Object.freeze([
    Object.freeze({ target: "state", key: "outputs", valueType: "json", default: [] }),
]);
const ITEM_TYPE_OPTIONS = Object.freeze(["float64", "int32", "boolean", "string", "json"]);
const ITEM_TYPE_SETTINGS = Object.freeze([
    Object.freeze({
        target: "state",
        key: "itemType",
        valueType: "enum",
        default: "float64",
        options: ITEM_TYPE_OPTIONS,
    }),
]);
const ARRAY_LITERAL_SETTINGS = Object.freeze([
    ...ITEM_TYPE_SETTINGS,
    Object.freeze({ target: "storedData", key: null, valueType: "json", default: [] }),
]);
const COMPILED_PROGRAM_SETTINGS = Object.freeze([
    Object.freeze({ target: "state", key: "compiledProgram", valueType: "json", default: null }),
]);
const ARRAY_GET_SETTINGS = Object.freeze([
    ...ITEM_TYPE_SETTINGS,
    Object.freeze({ target: "state", key: "fallback", valueType: "json", default: null }),
]);
const JSON_VALUE_TYPE_SETTING = Object.freeze({
    target: "state",
    key: "valueType",
    valueType: "enum",
    default: "json",
    options: ITEM_TYPE_OPTIONS,
});
const JSON_PATH_SETTING = Object.freeze({
    target: "state",
    key: "path",
    valueType: "string",
    default: "",
});
const JSON_GET_SETTINGS = Object.freeze([
    JSON_PATH_SETTING,
    JSON_VALUE_TYPE_SETTING,
    Object.freeze({ target: "state", key: "fallback", valueType: "json", default: null }),
]);
const JSON_SET_SETTINGS = Object.freeze([
    JSON_PATH_SETTING,
    JSON_VALUE_TYPE_SETTING,
]);
const JSON_PATH_SETTINGS = Object.freeze([JSON_PATH_SETTING]);

function entry(type, name, category, blockClass, keywords, options = {}) {
    return {
        type,
        name,
        category,
        keywords: [...keywords],
        placeable: options.placeable !== false,
        deprecated: options.deprecated === true,
        settings: options.settings || NO_SETTINGS,
        requiresSignals: options.requiresSignals === true,
        blockClass,
        notes: options.notes || null,
    };
}

/** @type {{ type: string, name: string, category: string, keywords: string[], placeable: boolean, deprecated: boolean, settings: object[], requiresSignals: boolean, blockClass: Function, notes: string|null }[]} */
export const UNIT_CATALOG_META = [
    entry("NumberUnitClass", "Number", "expressions", NumberUnitClass, ["number", "float", "constant"], { settings: NUMBER_SETTINGS }),
    entry("CalculationBlock", "Calculation", "expressions", CalculationBlock, ["calculate", "arithmetic", "legacy"], { placeable: false, deprecated: true }),
    entry("RandomNumberBlock", "Random Number", "expressions", RandomNumberBlock, ["random", "rng", "uniform"]),
    entry("PIBlock", "π (Pi)", "constants", PIBlock, ["pi", "circle", "3.14159"]),
    entry("EBlock", "e (Euler's Number)", "constants", EBlock, ["euler", "exponential"]),
    entry("TauBlock", "τ (Tau)", "constants", TauBlock, ["tau", "circle", "2 pi"]),
    entry("GoldenRatioBlock", "Golden Ratio (φ)", "constants", GoldenRatioBlock, ["phi", "golden ratio"]),
    entry("IntegerBlock", "Integer", "math", IntegerBlock, ["integer", "int32", "constant"], { settings: INTEGER_SETTINGS }),
    entry("AddBlock", "Add", "math", AddBlock, ["add", "plus", "sum", "arithmetic"]),
    entry("SubtractBlock", "Subtract", "math", SubtractBlock, ["subtract", "minus", "difference"]),
    entry("MultiplyBlock", "Multiply", "math", MultiplyBlock, ["multiply", "product", "times"]),
    entry("DivideBlock", "Divide", "math", DivideBlock, ["divide", "quotient"]),
    entry("ModuloBlock", "Modulo", "math", ModuloBlock, ["modulo", "remainder", "mod"]),
    entry("PowerBlock", "Power", "math", PowerBlock, ["power", "exponent", "pow"]),
    entry("MinimumBlock", "Minimum", "math", MinimumBlock, ["min", "minimum"]),
    entry("MaximumBlock", "Maximum", "math", MaximumBlock, ["max", "maximum"]),
    entry("NegateBlock", "Negate", "math", NegateBlock, ["negate", "negative", "unary"]),
    entry("AbsoluteBlock", "Absolute", "math", AbsoluteBlock, ["abs", "absolute", "magnitude"]),
    entry("SignBlock", "Sign", "math", SignBlock, ["sign", "signum"]),
    entry("SquareRootBlock", "Square Root", "math", SquareRootBlock, ["sqrt", "root"]),
    entry("ExponentialBlock", "Exponential", "math", ExponentialBlock, ["exp", "euler"]),
    entry("NaturalLogBlock", "Natural Log", "math", NaturalLogBlock, ["ln", "log", "logarithm"]),
    entry("Log10Block", "Log10", "math", Log10Block, ["log10", "logarithm"]),
    entry("ClampBlock", "Clamp", "math", ClampBlock, ["clamp", "limit", "bounds"]),
    entry("LerpBlock", "Lerp", "math", LerpBlock, ["lerp", "mix", "interpolate"]),
    entry("InverseLerpBlock", "Inverse Lerp", "math", InverseLerpBlock, ["inverse lerp", "unlerp"]),
    entry("SmoothstepBlock", "Smoothstep", "math", SmoothstepBlock, ["smoothstep", "hermite"]),
    entry("DeadbandBlock", "Deadband", "math", DeadbandBlock, ["deadband", "dead zone"]),
    entry("SinBlock", "Sin", "math", SinBlock, ["sin", "sine", "trig"]),
    entry("CosBlock", "Cos", "math", CosBlock, ["cos", "cosine", "trig"]),
    entry("TanBlock", "Tan", "math", TanBlock, ["tan", "tangent", "trig"]),
    entry("AsinBlock", "Asin", "math", AsinBlock, ["asin", "arcsin", "trig"]),
    entry("AcosBlock", "Acos", "math", AcosBlock, ["acos", "arccos", "trig"]),
    entry("AtanBlock", "Atan", "math", AtanBlock, ["atan", "arctan", "trig"]),
    entry("DegreesToRadiansBlock", "Degrees to Radians", "math", DegreesToRadiansBlock, ["degrees", "radians", "convert"]),
    entry("RadiansToDegreesBlock", "Radians to Degrees", "math", RadiansToDegreesBlock, ["radians", "degrees", "convert"]),
    entry("WrapRadiansBlock", "Wrap Radians", "math", WrapRadiansBlock, ["wrap", "angle", "tau", "pi"]),
    entry("Atan2Block", "Atan2", "math", Atan2Block, ["atan2", "heading", "angle"]),
    entry("MakeVec2Block", "Make Vec2", "geometry", MakeVec2Block, ["vec2", "vector", "make", "compose"]),
    entry("SplitVec2Block", "Split Vec2", "geometry", SplitVec2Block, ["vec2", "vector", "split", "unpack"]),
    entry("AddVec2Block", "Add Vec2", "geometry", AddVec2Block, ["vec2", "vector", "add", "plus"]),
    entry("SubtractVec2Block", "Subtract Vec2", "geometry", SubtractVec2Block, ["vec2", "vector", "subtract", "minus"]),
    entry("ScaleVec2Block", "Scale Vec2", "geometry", ScaleVec2Block, ["vec2", "vector", "scale", "multiply"]),
    entry("DotVec2Block", "Dot Vec2", "geometry", DotVec2Block, ["vec2", "vector", "dot", "product"]),
    entry("LengthVec2Block", "Length Vec2", "geometry", LengthVec2Block, ["vec2", "vector", "length", "magnitude"]),
    entry("NormalizeVec2Block", "Normalize Vec2", "geometry", NormalizeVec2Block, ["vec2", "vector", "normalize", "unit"]),
    entry("DistanceVec2Block", "Distance Vec2", "geometry", DistanceVec2Block, ["vec2", "vector", "distance"]),
    entry("MakeVec3Block", "Make Vec3", "geometry", MakeVec3Block, ["vec3", "vector", "make", "compose"]),
    entry("SplitVec3Block", "Split Vec3", "geometry", SplitVec3Block, ["vec3", "vector", "split", "unpack"]),
    entry("AddVec3Block", "Add Vec3", "geometry", AddVec3Block, ["vec3", "vector", "add", "plus"]),
    entry("SubtractVec3Block", "Subtract Vec3", "geometry", SubtractVec3Block, ["vec3", "vector", "subtract", "minus"]),
    entry("ScaleVec3Block", "Scale Vec3", "geometry", ScaleVec3Block, ["vec3", "vector", "scale", "multiply"]),
    entry("DotVec3Block", "Dot Vec3", "geometry", DotVec3Block, ["vec3", "vector", "dot", "product"]),
    entry("LengthVec3Block", "Length Vec3", "geometry", LengthVec3Block, ["vec3", "vector", "length", "magnitude"]),
    entry("NormalizeVec3Block", "Normalize Vec3", "geometry", NormalizeVec3Block, ["vec3", "vector", "normalize", "unit"]),
    entry("DistanceVec3Block", "Distance Vec3", "geometry", DistanceVec3Block, ["vec3", "vector", "distance"]),
    entry("CrossVec3Block", "Cross Vec3", "geometry", CrossVec3Block, ["vec3", "vector", "cross", "product"]),
    entry("MakePose2DBlock", "Make Pose 2D", "geometry", MakePose2DBlock, ["pose", "pose2d", "yaw", "make"]),
    entry("SplitPose2DBlock", "Split Pose 2D", "geometry", SplitPose2DBlock, ["pose", "pose2d", "yaw", "split"]),
    entry("MakePose3DBlock", "Make Pose 3D", "geometry", MakePose3DBlock, ["pose", "pose3d", "euler", "make"]),
    entry("SplitPose3DBlock", "Split Pose 3D", "geometry", SplitPose3DBlock, ["pose", "pose3d", "euler", "split"]),
    entry("BooleanBlock", "Boolean", "logic", BooleanBlock, ["boolean", "bool", "true", "false", "constant"], { settings: BOOLEAN_SETTINGS }),
    entry("NotBlock", "Not", "logic", NotBlock, ["not", "invert", "negate"]),
    entry("AndBlock", "And", "logic", AndBlock, ["and", "conjunction", "all"]),
    entry("OrBlock", "Or", "logic", OrBlock, ["or", "disjunction", "any"]),
    entry("XorBlock", "Xor", "logic", XorBlock, ["xor", "exclusive"]),
    entry("EqualBlock", "Equal", "logic", EqualBlock, ["equal", "eq", "compare"]),
    entry("NotEqualBlock", "Not Equal", "logic", NotEqualBlock, ["not equal", "neq", "compare"]),
    entry("LessBlock", "Less", "logic", LessBlock, ["less", "lt", "compare"]),
    entry("LessEqualBlock", "Less Equal", "logic", LessEqualBlock, ["less equal", "lte"]),
    entry("GreaterBlock", "Greater", "logic", GreaterBlock, ["greater", "gt"]),
    entry("GreaterEqualBlock", "Greater Equal", "logic", GreaterEqualBlock, ["greater equal", "gte"]),
    entry("NearlyEqualBlock", "Nearly Equal", "logic", NearlyEqualBlock, ["nearly", "approx", "epsilon"]),
    entry("IsFiniteBlock", "Is Finite", "logic", IsFiniteBlock, ["finite", "nan", "infinity"]),
    entry("PreviousBlock", "Previous", "control", PreviousBlock, ["previous", "delay", "hold", "z1"]),
    entry("ValueChangedBlock", "Value Changed", "control", ValueChangedBlock, ["changed", "delta", "edge"]),
    entry("RisingEdgeBlock", "Rising Edge", "control", RisingEdgeBlock, ["rising", "edge", "pulse"]),
    entry("FallingEdgeBlock", "Falling Edge", "control", FallingEdgeBlock, ["falling", "edge", "pulse"]),
    entry("DebounceBlock", "Debounce", "control", DebounceBlock, ["debounce", "stable"]),
    entry("HysteresisBlock", "Hysteresis", "control", HysteresisBlock, ["hysteresis", "schmitt", "band"]),
    entry("PulseBlock", "Pulse", "control", PulseBlock, ["pulse", "oneshot", "timer"]),
    entry("StopwatchBlock", "Stopwatch", "control", StopwatchBlock, ["stopwatch", "elapsed", "timer"]),
    entry("MovingAverageBlock", "Moving Average", "control", MovingAverageBlock, ["average", "filter", "window"]),
    entry("MedianFilterBlock", "Median Filter", "control", MedianFilterBlock, ["median", "filter", "window"]),
    entry("SlewRateBlock", "Slew Rate", "control", SlewRateBlock, ["slew", "rate", "limit"]),
    entry("IntegratorBlock", "Integrator", "control", IntegratorBlock, ["integrator", "accumulate", "integral"]),
    entry("DerivativeBlock", "Derivative", "control", DerivativeBlock, ["derivative", "difference", "slope"]),
    entry("PidControllerBlock", "PID Controller", "control", PidControllerBlock, ["pid", "controller", "anti-windup"]),
    entry("JsonBlock", "JSON", "objects", JsonBlock, ["json", "object", "constant", "literal"], { settings: JSON_SETTINGS }),
    entry("JsonGetBlock", "JSON Get", "objects", JsonGetBlock, ["json", "get", "path"], {
        settings: JSON_GET_SETTINGS,
        notes: "state.valueType is float64|int32|boolean|string|json. Ports resolve to that type.",
    }),
    entry("JsonSetBlock", "JSON Set", "objects", JsonSetBlock, ["json", "set", "path"], {
        settings: JSON_SET_SETTINGS,
        notes: "state.valueType is float64|int32|boolean|string|json.",
    }),
    entry("JsonHasBlock", "JSON Has", "objects", JsonHasBlock, ["json", "has", "path", "exists"], { settings: JSON_PATH_SETTINGS }),
    entry("JsonDeleteBlock", "JSON Delete", "objects", JsonDeleteBlock, ["json", "delete", "path", "remove"], { settings: JSON_PATH_SETTINGS }),
    entry("JsonMergeBlock", "JSON Merge", "objects", JsonMergeBlock, ["json", "merge", "assign"]),
    entry("NoiseBlock", "Noise Texture (tex1d)", "texture1d", NoiseBlock, ["noise", "texture", "tex1d"]),
    entry("MaskBlock", "Mask Texture (tex1d)", "texture1d", MaskBlock, ["mask", "texture", "tex1d"]),
    entry("MultiplyTexBlock", "Multiply Textures", "texture1d", MultiplyTexBlock, ["multiply", "texture", "tex1d"]),
    entry("ScaleBlock", "Scale Matrix (tex1d)", "texture1d", ScaleBlock, ["scale", "texture", "tex1d", "scalar", "legacy"], { placeable: false, deprecated: true }),
    entry("ScaleTextureBlock", "Scale Texture", "texture1d", ScaleTextureBlock, ["scale", "texture", "tex1d", "scalar"]),
    entry("AddTextureBlock", "Add Textures", "texture1d", AddTextureBlock, ["add", "texture", "tex1d"]),
    entry("SubtractTextureBlock", "Subtract Textures", "texture1d", SubtractTextureBlock, ["subtract", "texture", "tex1d"]),
    entry("ClampTextureBlock", "Clamp Texture", "texture1d", ClampTextureBlock, ["clamp", "texture", "tex1d"]),
    entry("InvertTextureBlock", "Invert Texture", "texture1d", InvertTextureBlock, ["invert", "texture", "tex1d"]),
    entry("TerrainNoiseBlock", "Terrain Noise (tex1d)", "terrain", TerrainNoiseBlock, ["terrain", "noise", "heightmap"]),
    entry("NormalizeTextureBlock", "Normalize Texture (tex1d)", "terrain", NormalizeTextureBlock, ["normalize", "texture"]),
    entry("BlendTextureBlock", "Blend Texture (tex1d)", "terrain", BlendTextureBlock, ["blend", "mix", "texture"]),
    entry("TerraceTextureBlock", "Terrace Texture (tex1d)", "terrain", TerraceTextureBlock, ["terrace", "steps", "texture"]),
    entry("HeightToSlopeBlock", "Height To Slope (tex1d)", "terrain", HeightToSlopeBlock, ["height", "slope", "texture"]),
    entry("SampleTextureBlock", "Sample Texture (tex1d → float64)", "sensorflow", SampleTextureBlock, ["sample", "texture", "sensor"]),
    entry("LowPassFilterBlock", "Low Pass Filter", "sensorflow", LowPassFilterBlock, ["filter", "smooth", "ema"]),
    entry("RateLimiterBlock", "Rate Limiter", "sensorflow", RateLimiterBlock, ["rate", "limit", "slew"]),
    entry("SensorFusionBlock", "Sensor Fusion", "sensorflow", SensorFusionBlock, ["sensor", "fusion", "weighted"]),
    entry("ThresholdGateBlock", "Threshold Gate", "sensorflow", ThresholdGateBlock, ["threshold", "range", "gate"]),
    entry("RandomRangeBlock", "Random Range", "randomization", RandomRangeBlock, ["random", "range", "rng"]),
    entry("SeededRandomBlock", "Seeded Random", "randomization", SeededRandomBlock, ["seed", "random", "deterministic"]),
    entry("GaussianNoiseBlock", "Gaussian Noise", "randomization", GaussianNoiseBlock, ["gaussian", "normal", "noise"]),
    entry("JitterBlock", "Jitter", "randomization", JitterBlock, ["jitter", "noise", "random"]),
    entry("WeightedSelectBlock", "Weighted Select", "randomization", WeightedSelectBlock, ["weighted", "select", "probability"]),
    entry("RemapRangeBlock", "Remap Range", "randomization", RemapRangeBlock, ["remap", "range", "map"]),
    entry("Float64ToInt32Block", "Float64 to Int32", "conversions", Float64ToInt32Block, ["convert", "float", "integer"]),
    entry("Int32ToFloat64Block", "Int32 to Float64", "conversions", Int32ToFloat64Block, ["convert", "integer", "float"]),
    entry("FloorToIntBlock", "Floor to Int", "conversions", FloorToIntBlock, ["floor", "convert", "integer"]),
    entry("CeilToIntBlock", "Ceil to Int", "conversions", CeilToIntBlock, ["ceil", "convert", "integer"]),
    entry("RoundToIntBlock", "Round to Int", "conversions", RoundToIntBlock, ["round", "convert", "integer"]),
    entry("TruncateToIntBlock", "Truncate to Int", "conversions", TruncateToIntBlock, ["truncate", "convert", "integer"]),
    entry("BooleanToIntBlock", "Boolean to Int", "conversions", BooleanToIntBlock, ["boolean", "integer", "convert"]),
    entry("BooleanToFloatBlock", "Boolean to Float", "conversions", BooleanToFloatBlock, ["boolean", "float", "convert"]),
    entry("IntToBooleanBlock", "Int to Boolean", "conversions", IntToBooleanBlock, ["integer", "boolean", "convert"]),
    entry("FloatToBooleanBlock", "Float to Boolean", "conversions", FloatToBooleanBlock, ["float", "boolean", "convert"]),
    entry("FloatToStringBlock", "Float to String", "conversions", FloatToStringBlock, ["float", "string", "convert"]),
    entry("IntToStringBlock", "Int to String", "conversions", IntToStringBlock, ["integer", "string", "convert"]),
    entry("BooleanToStringBlock", "Boolean to String", "conversions", BooleanToStringBlock, ["boolean", "string", "convert"]),
    entry("ToStringBlock", "To String", "conversions", ToStringBlock, ["to", "string", "convert", "stringify", "int32", "float64"]),
    entry("StringToFloatBlock", "String to Float", "conversions", StringToFloatBlock, ["string", "float", "parse"]),
    entry("StringToIntBlock", "String to Int", "conversions", StringToIntBlock, ["string", "integer", "parse"]),
    entry("StringToBooleanBlock", "String to Boolean", "conversions", StringToBooleanBlock, ["string", "boolean", "parse"]),
    entry("ParseJsonBlock", "Parse JSON", "conversions", ParseJsonBlock, ["parse", "json", "string"]),
    entry("StringifyJsonBlock", "Stringify JSON", "conversions", StringifyJsonBlock, ["stringify", "json", "string"]),
    entry("StringToRoadIdBlock", "String to Road ID", "conversions", StringToRoadIdBlock, ["string", "road", "id", "convert"]),
    entry("RoadIdToStringBlock", "Road ID to String", "conversions", RoadIdToStringBlock, ["road", "id", "string", "convert"]),
    entry("StringToTextureIdBlock", "String to Texture ID", "conversions", StringToTextureIdBlock, ["string", "texture", "id", "convert"]),
    entry("TextureIdToStringBlock", "Texture ID to String", "conversions", TextureIdToStringBlock, ["texture", "id", "string", "convert"]),
    entry("StringBlock", "String", "objects", StringBlock, ["string", "text", "constant"], { settings: STRING_SETTINGS }),
    entry("TextureImportBlock", "Texture Import", "objects", TextureImportBlock, ["texture", "import", "asset", "id"], { settings: STRING_SETTINGS }),
    entry("ConcatStringBlock", "Concat String", "strings", ConcatStringBlock, ["concat", "join", "string"]),
    entry("StringLengthBlock", "String Length", "strings", StringLengthBlock, ["length", "string", "count"]),
    entry("StringContainsBlock", "String Contains", "strings", StringContainsBlock, ["contains", "includes", "string"]),
    entry("StringStartsWithBlock", "String Starts With", "strings", StringStartsWithBlock, ["starts with", "prefix", "string"]),
    entry("StringEndsWithBlock", "String Ends With", "strings", StringEndsWithBlock, ["ends with", "suffix", "string"]),
    entry("TrimStringBlock", "Trim String", "strings", TrimStringBlock, ["trim", "whitespace", "string"]),
    entry("LowercaseStringBlock", "Lowercase String", "strings", LowercaseStringBlock, ["lowercase", "lower", "string"]),
    entry("UppercaseStringBlock", "Uppercase String", "strings", UppercaseStringBlock, ["uppercase", "upper", "string"]),
    entry("SliceStringBlock", "Slice String", "strings", SliceStringBlock, ["slice", "substring", "string"]),
    entry("ReplaceStringBlock", "Replace String", "strings", ReplaceStringBlock, ["replace", "substitute", "string"]),
    entry("SplitStringBlock", "Split String", "strings", SplitStringBlock, ["split", "array", "string"]),
    entry("JoinStringBlock", "Join String", "strings", JoinStringBlock, ["join", "array", "string"]),
    entry("ArrayLiteralBlock", "Array Literal", "collections", ArrayLiteralBlock, ["array", "literal", "list"], {
        settings: ARRAY_LITERAL_SETTINGS,
        notes: "state.itemType is float64|int32|boolean|string|json. Ports resolve to array[itemType].",
    }),
    entry("ArrayLengthBlock", "Array Length", "collections", ArrayLengthBlock, ["array", "length", "count"], {
        settings: ITEM_TYPE_SETTINGS,
        notes: "state.itemType is float64|int32|boolean|string|json. Ports resolve to array[itemType].",
    }),
    entry("ArrayGetBlock", "Array Get", "collections", ArrayGetBlock, ["array", "get", "index"], {
        settings: ARRAY_GET_SETTINGS,
        notes: "state.itemType is float64|int32|boolean|string|json. Out-of-range reads return fallback and found:false.",
    }),
    entry("ArraySetBlock", "Array Set", "collections", ArraySetBlock, ["array", "set", "index"], {
        settings: ITEM_TYPE_SETTINGS,
        notes: "Out-of-range writes leave the array unchanged with changed:false.",
    }),
    entry("ArrayAppendBlock", "Array Append", "collections", ArrayAppendBlock, ["array", "append", "push"], { settings: ITEM_TYPE_SETTINGS }),
    entry("ArrayConcatBlock", "Array Concat", "collections", ArrayConcatBlock, ["array", "concat", "join"], { settings: ITEM_TYPE_SETTINGS }),
    entry("ArraySliceBlock", "Array Slice", "collections", ArraySliceBlock, ["array", "slice", "range"], { settings: ITEM_TYPE_SETTINGS }),
    entry("ArrayContainsBlock", "Array Contains", "collections", ArrayContainsBlock, ["array", "contains", "includes"], { settings: ITEM_TYPE_SETTINGS }),
    entry("LinspaceBlock", "Linspace", "collections", LinspaceBlock, ["linspace", "range", "sample"]),
    entry("IfBlock", "If Statement", "statements", IfBlock, ["if", "condition", "select"]),
    entry("EqualityBlock", "Comparison (==, !=, >, <, >=, <=)", "statements", EqualityBlock, ["compare", "equality", "legacy"], { placeable: false, deprecated: true, settings: EQUALITY_SETTINGS }),
    entry("ConjugationBlock", "Conjunction (AND, OR)", "statements", ConjugationBlock, ["and", "or", "xor", "legacy"], { placeable: false, deprecated: true, settings: CONJUGATION_SETTINGS }),
    entry("NopBlock", "Nop", "statements", NopBlock, ["nop", "unit", "sequence"]),
    entry("IgnoreBlock", "Ignore", "statements", IgnoreBlock, ["ignore", "discard", "unit"]),
    entry("SequenceBlock", "Sequence", "statements", SequenceBlock, ["sequence", "then", "control"]),
    entry("PassthroughBlock", "Passthrough", "statements", PassthroughBlock, ["passthrough", "identity", "unit"]),
    entry("RepeatProgramBlock", "Repeat Program", "statements", RepeatProgramBlock, ["repeat", "loop", "program"], {
        settings: COMPILED_PROGRAM_SETTINGS,
        notes: "Loops a compiled child artifact. Reserved program inputs index and item are supplied per iteration. Count is clamped to 256.",
    }),
    entry("ProgramInputBlock", "Program Input", "program", ProgramInputBlock, ["program", "input", "parameter"], { settings: PROGRAM_INPUT_SETTINGS }),
    entry("OutputNodeBlock", "OutputNode", "program", OutputNodeBlock, ["program", "output", "head"], {
        placeable: false,
        settings: OUTPUT_NODE_SETTINGS,
        notes: "Graph head output node. Configure via graph.outputNodeConfig / script_update_unit on the head uuid (default head-uuid). Do not script_add_unit this type.",
    }),
    entry("ReadSignalBlock", "Read Signal", "signals", ReadSignalBlock, ["read", "signal", "value"]),
    entry("WriteSignalBlock", "Write Signal", "signals", WriteSignalBlock, ["write", "signal", "publish"]),
    entry("SignalExistsBlock", "Signal Exists", "signals", SignalExistsBlock, ["signal", "exists", "available"]),
    entry("SignalAgeBlock", "Signal Age", "signals", SignalAgeBlock, ["signal", "age", "stale"]),
    entry("SignalChangedBlock", "Signal Changed", "signals", SignalChangedBlock, ["signal", "changed", "revision"]),
    entry("SignalLatchBlock", "Signal Latch", "signals", SignalLatchBlock, ["signal", "latch", "hold"]),
    entry("SignalDefaultBlock", "Signal Default", "signals", SignalDefaultBlock, ["signal", "default", "fallback"]),
    entry("StoreNamespaceBlock", "Store Namespace", "signals", StoreNamespaceBlock, ["signal", "namespace", "path"]),
    entry("TopicSnapshotBlock", "Topic Snapshot", "topics", TopicSnapshotBlock, ["topic", "snapshot", "message"], { requiresSignals: true }),
    entry("TopicFieldBlock", "Topic Field", "topics", TopicFieldBlock, ["topic", "field", "message"]),
    entry("BuildTopicMessageBlock", "Build Topic Message", "topics", BuildTopicMessageBlock, ["topic", "build", "message"]),
    entry("StagePublishBlock", "Stage Publish", "topics", StagePublishBlock, ["topic", "publish", "stage"]),
    entry("TopicStaleGateBlock", "Topic Stale Gate", "topics", TopicStaleGateBlock, ["topic", "stale", "gate"]),
    entry("TopicMetadataBlock", "Topic Metadata", "topics", TopicMetadataBlock, ["topic", "metadata", "status"]),
    entry("VehicleSnapshotBlock", "Vehicle Snapshot", "simulator", VehicleSnapshotBlock, ["vehicle", "snapshot", "ego"], { requiresSignals: true }),
    entry("VehiclePoseBlock", "Vehicle Pose", "simulator", VehiclePoseBlock, ["vehicle", "pose", "ego"], { requiresSignals: true }),
    entry("VehicleVelocityBlock", "Vehicle Velocity", "simulator", VehicleVelocityBlock, ["vehicle", "velocity", "speed"], { requiresSignals: true }),
    entry("VehicleDimensionsBlock", "Vehicle Dimensions", "simulator", VehicleDimensionsBlock, ["vehicle", "dimensions", "size"], { requiresSignals: true }),
    entry("DeviceSnapshotBlock", "Device Snapshot", "simulator", DeviceSnapshotBlock, ["device", "sensor", "snapshot"], { requiresSignals: true }),
    entry("SimulationSnapshotBlock", "Simulation Snapshot", "simulator", SimulationSnapshotBlock, ["simulation", "snapshot", "clock"], { requiresSignals: true }),
    entry("ScenarioSnapshotBlock", "Scenario Snapshot", "simulator", ScenarioSnapshotBlock, ["scenario", "snapshot", "status"], { requiresSignals: true }),
    entry("ObjectSnapshotBlock", "Object Snapshot", "simulator", ObjectSnapshotBlock, ["object", "snapshot", "target"], { requiresSignals: true }),
    entry("VehicleStateBlock", "Vehicle State", "simulator", VehicleStateBlock, ["vehicle", "state", "pose", "adapter"], { requiresSignals: true }),
    entry("DeviceStateBlock", "Device State", "simulator", DeviceStateBlock, ["device", "state", "pose", "adapter"], { requiresSignals: true }),
    entry("SimulationClockBlock", "Simulation Clock", "simulator", SimulationClockBlock, ["simulation", "clock", "dt", "adapter"], { requiresSignals: true }),
    entry("ScenarioStatusBlock", "Scenario Status", "simulator", ScenarioStatusBlock, ["scenario", "status", "terminal", "adapter"], { requiresSignals: true }),
    entry("SampleRoadBlock", "Sample Road", "simulator", SampleRoadBlock, ["road", "sample", "pose", "edge"]),
    entry("GetNearestRoadBlock", "Get Nearest Road", "simulator", GetNearestRoadBlock, ["nearest", "road", "pose", "edge"]),
    entry("SpawnPropBlock", "Spawn Prop", "simulator", SpawnPropBlock, ["spawn", "prop", "barrel", "episode"], {
        notes: "Episode overlay upsert. Bind the graph to episode-reset. Ids are episode:{scriptId}:{n} when omitted. Does not mutate the environment document.",
    }),
    entry("ScatterFeaturesBlock", "Scatter Features", "simulator", ScatterFeaturesBlock, ["scatter", "barrel", "shoulder", "route"], {
        notes: "One-node shoulder+lane scatter. Requires exactly one of route or edgeId. Spawn is upsert-by-id onto the episode overlay.",
    }),
    entry("WaypointListBlock", "Waypoint List", "mission", WaypointListBlock, ["waypoint", "route", "list"]),
    entry("CurrentWaypointBlock", "Current Waypoint", "mission", CurrentWaypointBlock, ["waypoint", "current", "mission"]),
    entry("AdvanceWaypointBlock", "Advance Waypoint", "mission", AdvanceWaypointBlock, ["waypoint", "advance", "mission"]),
    entry("ReachedWaypointBlock", "Reached Waypoint", "mission", ReachedWaypointBlock, ["waypoint", "reached", "distance"]),
    entry("MissionStateBlock", "Mission State", "mission", MissionStateBlock, ["mission", "state", "status"]),
    entry("SetMissionStateBlock", "Set Mission State", "mission", SetMissionStateBlock, ["mission", "state", "set"]),
    entry("RouteProgressBlock", "Route Progress", "mission", RouteProgressBlock, ["route", "progress", "mission"]),
    entry("FollowRouteBlock", "Follow Route", "mission", FollowRouteBlock, ["route", "follow", "command"]),
    entry("FollowRouteSectionBlock", "Follow Route Section", "mission", FollowRouteSectionBlock, ["route", "section", "follow"]),
    entry("RouteSectionCountBlock", "Route Section Count", "mission", RouteSectionCountBlock, ["route", "section", "count"]),
    entry("WaypointAtIndexBlock", "Waypoint At Index", "mission", WaypointAtIndexBlock, ["waypoint", "index", "route"]),
    entry("SplitWaypointBlock", "Split Waypoint", "mission", SplitWaypointBlock, ["waypoint", "split", "position"]),
    entry("RouteLengthBlock", "Route Length", "mission", RouteLengthBlock, ["route", "length", "distance"]),
    entry("DistanceToRouteEndBlock", "Distance To Route End", "mission", DistanceToRouteEndBlock, ["route", "distance", "end"]),
    entry("RouteTangentBlock", "Route Tangent", "mission", RouteTangentBlock, ["route", "tangent", "heading", "progress"]),
    entry("FrameAlongPathBlock", "Frame Along Path", "mission", FrameAlongPathBlock, ["frame", "path", "pose", "lateral"]),
    entry("MakeActorCommandBlock", "Make Actor Command", "mission", MakeActorCommandBlock, ["actor", "command", "vehicle"], {
        notes: "actorId is optional; omitted values become empty string.",
    }),
    entry("SplitActorCommandBlock", "Split Actor Command", "mission", SplitActorCommandBlock, ["actor", "command", "split"]),
    entry("ScenarioFlagReadBlock", "Scenario Flag Read", "mission", ScenarioFlagReadBlock, ["scenario", "flag", "read"]),
    entry("ScenarioFlagWriteBlock", "Scenario Flag Write", "mission", ScenarioFlagWriteBlock, ["scenario", "flag", "write"]),
    entry("OnSignalUpdateBlock", "On Signal Update", "bindings", OnSignalUpdateBlock, ["signal", "update", "trigger"]),
    entry("OnTickBlock", "On Tick", "bindings", OnTickBlock, ["tick", "frame", "trigger"]),
    entry("OnTimerBlock", "On Timer", "bindings", OnTimerBlock, ["timer", "interval", "trigger"]),
    entry("BindInputBlock", "Bind Input", "bindings", BindInputBlock, ["bind", "input", "signal"]),
    entry("BindOutputBlock", "Bind Output", "bindings", BindOutputBlock, ["bind", "output", "signal"]),
    entry("BindTriggerBlock", "Bind Trigger", "bindings", BindTriggerBlock, ["bind", "trigger", "signal"]),
    entry("ProbeSignalBlock", "Probe Signal", "diagnostics", ProbeSignalBlock, ["probe", "signal", "debug"]),
    entry("LogSignalBlock", "Log Signal", "diagnostics", LogSignalBlock, ["log", "signal", "debug"]),
    entry("LogMessageBlock", "Log Message", "diagnostics", LogMessageBlock, ["log", "message", "print", "console"]),
    entry("AssertSignalBlock", "Assert Signal", "diagnostics", AssertSignalBlock, ["assert", "signal", "test"]),
    entry("RecordSignalBlock", "Record Signal", "diagnostics", RecordSignalBlock, ["record", "signal", "history"]),
    entry("ReplaySignalBlock", "Replay Signal", "diagnostics", ReplaySignalBlock, ["replay", "signal", "history"]),
    entry("BindingStatusBlock", "Binding Status", "diagnostics", BindingStatusBlock, ["binding", "status", "diagnostic"]),
];
